<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>Symfony Logs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Date of log line</string>
			<key>match</key>
			<string>\[\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2}\]</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Debug event</string>
			<key>match</key>
			<string>([a-z]+)\.DEBUG</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Info event</string>
			<key>match</key>
			<string>([a-z]+)\.INFO</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Critical event</string>
			<key>match</key>
			<string>(([a-z]+)\.CRITICAL)|(([a-z]+)\.ERROR)|(([a-z]+)\.WARNING)</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String (class name or file)</string>
			<key>match</key>
			<string>\"[^\"]+\"</string>
			<key>name</key>
			<string>string.quoted.other</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.log</string>
	<key>uuid</key>
	<string>d7a6d65c-039f-4f6c-9e91-41a4d4593227</string>
</dict>
</plist>
